/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal.Administrador;

import com.mycompany.proyectofinal.Curso;
import com.mycompany.proyectofinal.ProyectoFinal;
import com.mycompany.proyectofinal.Usuario;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Alway
 */
public class EditarCursos extends javax.swing.JFrame {

    private Usuario usuario;

    public EditarCursos(Usuario usuario) {
        initComponents();
        LlenarComboBox();
        LlenarComboBoxProfesores();
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnRegresasr = new javax.swing.JButton();
        cbIdCurso = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtNombreCurso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSeccionCurso = new javax.swing.JTextField();
        txtProfeso = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        txtFechaFin = new javax.swing.JTextField();
        lblfechaFin = new javax.swing.JLabel();
        txtHoraInicio = new javax.swing.JTextField();
        lblHoraInicio = new javax.swing.JLabel();
        txtHoraFin = new javax.swing.JTextField();
        lblHoraFin = new javax.swing.JLabel();
        cbProfesorAsignado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Edicion de Cursos: ");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabel2.setText("id: ");

        btnRegresasr.setText("Regresar");
        btnRegresasr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresasrActionPerformed(evt);
            }
        });

        cbIdCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIdCursoActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre: ");

        jLabel5.setText("Fecha Inicio: ");

        jLabel4.setText("Seccion: ");

        txtProfeso.setText("Profesor: ");

        lblfechaFin.setText("Fecha Fin: ");

        lblHoraInicio.setText("Hora Inicio: ");

        lblHoraFin.setText("Hora Fin: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegresasr)
                            .addComponent(btnActualizar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(lblfechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblHoraInicio)
                                        .addComponent(lblHoraFin)
                                        .addComponent(txtProfeso))
                                    .addGap(27, 27, 27)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                        .addComponent(txtFechaFin)))
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel4))
                                    .addGap(30, 30, 30)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSeccionCurso)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbIdCurso, 0, 276, Short.MAX_VALUE)
                                            .addComponent(txtNombreCurso)))))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtHoraFin)
                        .addComponent(txtHoraInicio)
                        .addComponent(cbProfesorAsignado, 0, 261, Short.MAX_VALUE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbIdCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSeccionCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfechaFin)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraInicio)
                    .addComponent(txtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraFin)
                    .addComponent(txtHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProfeso)
                    .addComponent(cbProfesorAsignado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnActualizar)
                .addGap(27, 27, 27)
                .addComponent(btnRegresasr)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        try {
            Curso idCurso = (Curso) cbIdCurso.getSelectedItem();
            for (Curso curso : ProyectoFinal.listaCurso) {
                if (idCurso.getIdCurso().equals(curso.getIdCurso())) {
                    curso.setNombreCurso(txtNombreCurso.getText());
                    curso.setSeccionCurso(txtSeccionCurso.getText());
                    curso.setFechaInicio(dateFormat.parse(txtFechaInicio.getText()));
                    curso.setFechaFin(dateFormat.parse(txtFechaFin.getText().toString()));
                    curso.setUsuarioAsignado((Usuario) cbProfesorAsignado.getSelectedItem());
                    JOptionPane.showMessageDialog(this, "Se ha Actualizado el profesor correctamente");
                }
            }
        } catch (ParseException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnRegresasrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresasrActionPerformed
        MenuCurso menu = new MenuCurso(usuario);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresasrActionPerformed

    private void cbIdCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIdCursoActionPerformed
        LlenarInfoCurso();
    }//GEN-LAST:event_cbIdCursoActionPerformed

    private void LlenarComboBox() {
        for (Curso u : ProyectoFinal.listaCurso) {
            cbIdCurso.addItem(u);
        }
    }

    private void LlenarComboBoxProfesores() {
        for (Usuario u : ProyectoFinal.listaUsuario) {
            if (u.getRolUsuario().equals("Profesor")) {
                cbProfesorAsignado.addItem(u);
            }
        }
    }

    private void LlenarInfoCurso() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        try {
            Curso cbCarneUSuario = (Curso) cbIdCurso.getSelectedItem();
            for (Curso u : ProyectoFinal.listaCurso) {
                if (u.getIdCurso().equals(cbCarneUSuario.getIdCurso())) {
                    txtNombreCurso.setText(u.getNombreCurso());
                    txtSeccionCurso.setText(u.getSeccionCurso());
                    txtFechaInicio.setText(dateFormat.format(u.getFechaInicio()));
                    txtFechaFin.setText(dateFormat.format(u.getFechaFin()));
                    txtHoraInicio.setText(u.getHoraInicio());
                    txtHoraFin.setText(u.getHoraFin());
                    cbProfesorAsignado.setSelectedItem(u.getUsuarioAsignado());
                }
            }
        } catch (ClassFormatError e) {
            System.out.println(e);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnRegresasr;
    private javax.swing.JComboBox<Curso> cbIdCurso;
    private javax.swing.JComboBox<Usuario> cbProfesorAsignado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblHoraFin;
    private javax.swing.JLabel lblHoraInicio;
    private javax.swing.JLabel lblfechaFin;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtHoraFin;
    private javax.swing.JTextField txtHoraInicio;
    private javax.swing.JTextField txtNombreCurso;
    private javax.swing.JLabel txtProfeso;
    private javax.swing.JTextField txtSeccionCurso;
    // End of variables declaration//GEN-END:variables
}
