/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal.Administrador.Profesor;

import com.mycompany.proyectofinal.Curso;
import com.mycompany.proyectofinal.ProyectoFinal;
import com.mycompany.proyectofinal.Usuario;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Alway
 */
public class AgregarNota extends javax.swing.JFrame {

    private Usuario usuario;

    public AgregarNota(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        LlenarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnRegresasr = new javax.swing.JButton();
        cbIdCurso = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtNombreCurso = new javax.swing.JTextField();
        cbAlumnoCalificar = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtSeccionCurso = new javax.swing.JTextField();
        txtProfeso = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        txtNota = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("id: ");

        btnRegresasr.setText("Regresar");
        btnRegresasr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresasrActionPerformed(evt);
            }
        });

        cbIdCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIdCursoActionPerformed(evt);
            }
        });

        jLabel3.setText("Curso:");

        txtNombreCurso.setEditable(false);

        cbAlumnoCalificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlumnoCalificarActionPerformed(evt);
            }
        });

        jLabel4.setText("Seccion: ");

        txtSeccionCurso.setEditable(false);

        txtProfeso.setText("Alumno: ");

        jLabel1.setText("Asignacion de Notas: ");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabel5.setText("Nota:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegresasr)
                    .addComponent(btnActualizar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addComponent(txtProfeso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSeccionCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                .addComponent(cbIdCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbAlumnoCalificar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNota)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbIdCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSeccionCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProfeso)
                    .addComponent(cbAlumnoCalificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnActualizar)
                .addGap(27, 27, 27)
                .addComponent(btnRegresasr)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresasrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresasrActionPerformed
        MenuCursosProfesor menu = new MenuCursosProfesor(usuario);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresasrActionPerformed

    private void cbIdCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIdCursoActionPerformed
        LlenarInfoCurso();
        LlenarComboBoxUsuario();
    }//GEN-LAST:event_cbIdCursoActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
    Curso cursoSeleccionado = (Curso) cbIdCurso.getSelectedItem();
    Usuario alumnoSeleccionado = (Usuario) cbAlumnoCalificar.getSelectedItem();
    
    try {
        int notaFinal = Integer.parseInt(txtNota.getText());
        
        if (notaFinal > 100) {
            JOptionPane.showMessageDialog(null, "La nota no puede ser mayor a 100", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (cursoSeleccionado != null && alumnoSeleccionado != null) {
            for (Curso curso : ProyectoFinal.listaCurso) {
                if (curso.getIdCurso().equals(cursoSeleccionado.getIdCurso()) && curso.getAlumnoAsignado().contains(alumnoSeleccionado)) {
                    curso.agregarNota(alumnoSeleccionado, notaFinal);
                    JOptionPane.showMessageDialog(this, "Se ha agregado la nota para el alumno: " + alumnoSeleccionado.getNombreUsuario());
                    break;
                }
            }
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido para la nota", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void cbAlumnoCalificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlumnoCalificarActionPerformed

    }//GEN-LAST:event_cbAlumnoCalificarActionPerformed

    private void LlenarInfoCurso() {
        Curso cbCarneUSuario = (Curso) cbIdCurso.getSelectedItem();
        for (Curso u : ProyectoFinal.listaCurso) {
            if (u.getIdCurso().equals(cbCarneUSuario.getIdCurso())) {
                txtNombreCurso.setText(u.getNombreCurso());
                txtSeccionCurso.setText(u.getSeccionCurso());
            }
        }
    }

    private void LlenarComboBox() {
        for (Curso u : ProyectoFinal.listaCurso) {
            if(u.getUsuarioAsignado().getUsuarioLogin().equals(usuario.getUsuarioLogin())){
            cbIdCurso.addItem(u);
            }
        }
    }

    private void LlenarComboBoxUsuario() {
        cbAlumnoCalificar.removeAllItems();

        Curso cursoSeleccionado = (Curso) cbIdCurso.getSelectedItem();
        if (cursoSeleccionado != null) {
            for (Usuario alumno : cursoSeleccionado.getAlumnoAsignado()) {
                cbAlumnoCalificar.addItem(alumno);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnRegresasr;
    private javax.swing.JComboBox<Usuario> cbAlumnoCalificar;
    private javax.swing.JComboBox<Curso> cbIdCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtNombreCurso;
    private javax.swing.JTextField txtNota;
    private javax.swing.JLabel txtProfeso;
    private javax.swing.JTextField txtSeccionCurso;
    // End of variables declaration//GEN-END:variables
}
