/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal.alumno;

import com.mycompany.proyectofinal.Curso;
import com.mycompany.proyectofinal.ProyectoFinal;
import com.mycompany.proyectofinal.Usuario;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Alway
 */
public class DesasignacionCursoAlumno extends javax.swing.JFrame {

    private Usuario usuario;

    public DesasignacionCursoAlumno(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        LlenarComboBoxCurso();
        LlenarInfoAlumno();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombreCurso = new javax.swing.JTextField();
        btnAsignarCurso = new javax.swing.JButton();
        lblHoraFin = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbAlumnoAsignado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtSeccionCurso = new javax.swing.JTextField();
        txtProfeso = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        lblfechaFin = new javax.swing.JLabel();
        btnRegresasr = new javax.swing.JButton();
        txtHoraInicio = new javax.swing.JTextField();
        cbIdCurso = new javax.swing.JComboBox<>();
        lblHoraInicio = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHoraFin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNombreCurso.setEditable(false);

        btnAsignarCurso.setText("Desasignar");
        btnAsignarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarCursoActionPerformed(evt);
            }
        });

        lblHoraFin.setText("Hora Fin: ");

        jLabel5.setText("Fecha Inicio: ");

        jLabel4.setText("Seccion: ");

        txtSeccionCurso.setEditable(false);

        txtProfeso.setText("Alumno: ");

        txtFechaFin.setEditable(false);

        jLabel1.setText("Asignacion de Alumnos a cursos: ");

        jLabel2.setText("id: ");

        txtFechaInicio.setEditable(false);

        lblfechaFin.setText("Fecha Fin: ");

        btnRegresasr.setText("Regresar");
        btnRegresasr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresasrActionPerformed(evt);
            }
        });

        txtHoraInicio.setEditable(false);

        cbIdCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIdCursoActionPerformed(evt);
            }
        });

        lblHoraInicio.setText("Hora Inicio: ");

        jLabel3.setText("Nombre: ");

        txtHoraFin.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(lblfechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblHoraInicio)
                                        .addComponent(lblHoraFin)
                                        .addComponent(txtProfeso))
                                    .addGap(27, 27, 27)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                        .addComponent(txtFechaFin)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel4))
                                    .addGap(30, 30, 30)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSeccionCurso)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbIdCurso, 0, 276, Short.MAX_VALUE)
                                            .addComponent(txtNombreCurso))))
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAsignarCurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegresasr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtHoraFin)
                        .addComponent(txtHoraInicio)
                        .addComponent(cbAlumnoAsignado, 0, 261, Short.MAX_VALUE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbIdCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSeccionCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfechaFin)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraInicio)
                    .addComponent(txtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraFin)
                    .addComponent(txtHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProfeso)
                    .addComponent(cbAlumnoAsignado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAsignarCurso)
                .addGap(27, 27, 27)
                .addComponent(btnRegresasr)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsignarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarCursoActionPerformed
        Curso idCurso = (Curso) cbIdCurso.getSelectedItem();
        Usuario user = (Usuario) cbAlumnoAsignado.getSelectedItem();

        if (idCurso != null && user != null) {
            for (Curso curso : ProyectoFinal.listaCurso) {
                if (curso.getIdCurso().equals(idCurso.getIdCurso())) {
                    curso.eliminarAlumno(user);
                    JOptionPane.showMessageDialog(null, "Se ha desasignado el curso correctamente.");
                    break;
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un curso y un usuario.");
        }
    }//GEN-LAST:event_btnAsignarCursoActionPerformed

    private void btnRegresasrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresasrActionPerformed
        MenuCursosAlumno menu = new MenuCursosAlumno(usuario);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresasrActionPerformed

    private void cbIdCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIdCursoActionPerformed
        LlenarInfoCurso();
    }//GEN-LAST:event_cbIdCursoActionPerformed

    private void LlenarComboBoxCurso() {
        for (Curso u : ProyectoFinal.listaCurso) {
            cbIdCurso.addItem(u);
        }
    }

    private void LlenarInfoAlumno() {
        cbAlumnoAsignado.addItem(usuario);
    }

    private void LlenarInfoCurso() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        try {
            Curso idCurso = (Curso) cbIdCurso.getSelectedItem();
            for (Curso u : ProyectoFinal.listaCurso) {
                if (u.getIdCurso().equals(idCurso.getIdCurso())) {
                    txtNombreCurso.setText(u.getNombreCurso());
                    txtSeccionCurso.setText(u.getSeccionCurso());
                    txtFechaInicio.setText(dateFormat.format(u.getFechaInicio()));
                    txtFechaFin.setText(dateFormat.format(u.getFechaFin()));
                    txtHoraInicio.setText(u.getHoraInicio());
                    txtHoraFin.setText(u.getHoraFin());
                    return;
                }
            }
        } catch (ClassFormatError e) {
            System.out.println(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarCurso;
    private javax.swing.JButton btnRegresasr;
    private javax.swing.JComboBox<Usuario> cbAlumnoAsignado;
    private javax.swing.JComboBox<Curso> cbIdCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblHoraFin;
    private javax.swing.JLabel lblHoraInicio;
    private javax.swing.JLabel lblfechaFin;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtHoraFin;
    private javax.swing.JTextField txtHoraInicio;
    private javax.swing.JTextField txtNombreCurso;
    private javax.swing.JLabel txtProfeso;
    private javax.swing.JTextField txtSeccionCurso;
    // End of variables declaration//GEN-END:variables
}
