/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal.alumno;

import static com.mycompany.proyectofinal.Administrador.Profesor.MiPerfilProfesor.validarContra;
import com.mycompany.proyectofinal.Curso;
import com.mycompany.proyectofinal.ProyectoFinal;
import com.mycompany.proyectofinal.Usuario;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Alway
 */
public class MiPerfilAlumno extends javax.swing.JFrame {

    private Usuario usuario;

    public MiPerfilAlumno(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        lblIdUsuario.setText(usuario.getUsuarioId().toString());
        lblCarneUsuario.setText(usuario.getUsuarioLogin());
        lblNombreUsuario.setText(usuario.getNombreUsuario());
        lblApellidoUsuario.setText(usuario.getApellidoUsuario());
        txtPwd.setText(usuario.getPasswordUsuario());
        double promedio = calcularPromedioNotas(ProyectoFinal.listaCurso);
        lblPromedio.setText(String.format("%.2f", promedio));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCarneUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblApellidoUsuario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPromedio = new javax.swing.JLabel();
        lblIdUsuario = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        lblCarneSetter = new javax.swing.JLabel();
        txtPwd = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCarneUsuario.setText("jLabel4");

        jLabel3.setText("Mi Nombre: ");

        lblNombreUsuario.setText("jLabel4");

        jLabel4.setText("Mi Apellido: ");

        lblApellidoUsuario.setText("jLabel5");

        jLabel5.setText("Contraseña: ");

        jLabel1.setText("Mi Perfil: ");

        jLabel6.setText("Promedio: ");

        jLabel2.setText("Mi ID: ");

        lblPromedio.setText("jLabel7");

        lblIdUsuario.setText("jLabel3");

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblCarneSetter.setText("Mi Carné: ");

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCarneSetter)
                                .addGap(27, 27, 27)
                                .addComponent(lblCarneUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblApellidoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPromedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                                .addComponent(btnRegresar)
                                .addGap(15, 15, 15))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnRegresar))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblIdUsuario))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarneSetter)
                    .addComponent(lblCarneUsuario))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblNombreUsuario))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblApellidoUsuario))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblPromedio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        BienvenidaAlumno bienvenida = new BienvenidaAlumno(usuario);
        bienvenida.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        if (validarContra(txtPwd.getText())) {
            for (Usuario u : ProyectoFinal.listaUsuario) {
                if (usuario.getUsuarioId().equals(u.getUsuarioId()) && u.getRolUsuario().equals("Alumno")) {
                    u.setPasswordUsuario(txtPwd.getText());
                    JOptionPane.showMessageDialog(this, "Se ha actualizado la contraseña con exito");
                    break;
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Por favor valide que la contraseña cumpla con los requisitos.");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public double calcularPromedioNotas(List<Curso> listaCurso) {
        int sumaNotas = 0;
        int totalCursosConNotas = 0;

        for (Curso curso : listaCurso) {
            Integer nota = curso.getNota(usuario);
            if (nota != null) {
                sumaNotas += nota;
                totalCursosConNotas++;
            }
        }

        if (totalCursosConNotas == 0) {
            return 0.0;
        }

        return (double) sumaNotas / totalCursosConNotas;
    }

    public static boolean validarContra(String password) {
        String regex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d).{8,}$";

        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(password);
        return matcher.matches();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblApellidoUsuario;
    private javax.swing.JLabel lblCarneSetter;
    private javax.swing.JLabel lblCarneUsuario;
    private javax.swing.JLabel lblIdUsuario;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblPromedio;
    private javax.swing.JTextField txtPwd;
    // End of variables declaration//GEN-END:variables
}
